### ISSUE TITLE
Different domains in one batch

### ISSUE THREAD

**Issue by SnowdenLee** [wgchang/DSBN#10]
Hi, 
thanks for the interesting work. I'm wondering how this works if there are images from different domains in one batch. Will different BN be used for each image individually or?
Thanks a lot?

**Comment by woozch** [comment]
Hi. [SnowdenLee](https://github.com/SnowdenLee)
Since our algorithm assumes that the data are sampled from different domains, so we need information about which domain the data came from (domain label).
When data from multiple domains are merged into one, it must be able to be separated by source.

Here, the definition of "domain" should be seen as having a different distribution where a huge domain gap(usually performance drop) occurs during test.
